import type { ChatMessage } from "@/lib/conversation-types";

export const EMPTY_MESSAGES: ChatMessage[] = [];

export const MOCK_CONVERSATIONS: Record<string, ChatMessage[]> = {
	s1: [
		{
			id: "s1-u1",
			role: "user",
			text: "先把 UI 做好，整体风格参考 Lody。侧边栏、聊天区域和输入框都尽量保持一致的体验。",
			time: "11:18",
		},
		{
			id: "s1-a1",
			role: "assistant",
			text: "已经把基础视觉体系迁到 Pilo。聊天页继续沿用 Lody 的单列阅读布局：\n\n- 用户消息靠右使用轻量气泡\n- Pi 回复保持无外框正文\n- 工具活动收在正文之间\n- 输入区固定在底部并和消息列使用同一宽度\n\n这样后续接真实 RPC streaming 时只需要替换数据源。",
			time: "11:19",
			activity: [
				{
					id: "s1-a1-thinking",
					type: "thinking",
					text: "对比了消息列、活动信息和输入区的层级关系，保留低对比度与单列阅读结构。",
					status: "complete",
				},
				...[
					"src/App.tsx",
					"src/index.css",
					"src/ui/button.tsx",
					"src/ui/textarea.tsx",
				].map((path, index) => ({
					id: `s1-a1-tool-${index}`,
					type: "tool" as const,
					toolName: "read",
					args: { path },
					status: "complete" as const,
				})),
			],
		},
		{
			id: "s1-u2",
			role: "user",
			text: "输入框也直接参考 Lody，不要做成传统聊天软件那种很重的卡片。",
			time: "11:23",
		},
		{
			id: "s1-a2",
			role: "assistant",
			text: '可以。`session composer` 会保持低对比边框和紧凑 footer，模型、模式、附件和发送都收在同一行。\n\n```tsx\n<ChatComposer\n  value={draft}\n  onSubmit={sendMessage}\n  modelLabel="pi / default"\n/>\n```\n\n正文输入自动增高，最多 12 行。',
			time: "11:24",
		},
		{
			id: "s1-a2b",
			role: "assistant",
			text: [
				"先把现有问题列清楚：",
				"",
				"1. **消息列宽度**：滚动条出现时被压缩 8px，输入框 overlay 不受影响，两者左边缘错位。",
				"2. **底部遮挡**：composer 容器自带 `bg-background`，消息从后面被硬切，观感生硬。",
				"3. **Outline rail**：滚动位置高亮基于 `offsetTop`，长会话下没有节流，滚动掉帧。",
				"",
				"其中 1 和 2 是纯样式问题，一行 class 就能修；3 需要把 reading line 的计算移到 `requestAnimationFrame` 里合并。",
			].join("\n"),
			time: "11:26",
		},
		{
			id: "s1-u3",
			role: "user",
			text: "那先把 1 和 2 修了，宽度用 scrollbar-gutter 对齐，遮挡直接去掉白底让输入框自然盖住就行。",
			time: "11:28",
		},
		{
			id: "s1-a3",
			role: "assistant",
			text: [
				"改动落在 `chat-page.tsx`：",
				"",
				"```tsx",
				"// 滚动容器：恒定预留滚动条空间，消息列宽度不再跳动",
				'<div className="scrollbar-pro h-full overflow-y-auto [scrollbar-gutter:stable]" />',
				"",
				"// composer overlay：补齐同样的 8px，去掉 bg-background",
				'<div className="absolute inset-x-0 bottom-0 pr-2">',
				'	<ConversationColumn className="relative pb-3">',
				"</div>",
				"```",
				"",
				"这样消息直接延伸到底部，由 composer 自身的背景自然截断，滚动条出现与否列宽都一致。",
			].join("\n"),
			time: "11:29",
		},
		{
			id: "s1-u4",
			role: "user",
			text: "好，帮我跑一遍前端验证。",
			time: "11:31",
		},
		{
			id: "s1-a4",
			role: "assistant",
			text: "`pnpm format`、`pnpm check`、`pnpm build` 全部通过。构建只有一个已有的 chunk 体积警告，和这次改动无关。视觉效果需要你这边 `pnpm tauri dev` 确认。",
			time: "11:32",
			activity: ["pnpm format", "pnpm check", "pnpm build"].map(
				(command, index) => ({
					id: `s1-a4-tool-${index}`,
					type: "tool" as const,
					toolName: "bash",
					args: { command },
					status: "complete" as const,
				}),
			),
		},
		{
			id: "s1-u5",
			role: "user",
			text: "我看效果还行。接下来把 outline rail 的掉帧问题也处理一下？",
			time: "11:40",
		},
		{
			id: "s1-a5",
			role: "assistant",
			text: [
				"可以。现在的实现是 `onScroll` 每次触发都遍历 outline entries 并 setState，长会话下每秒能触发几十次。",
				"",
				"计划这样改：",
				"",
				"- `syncScrollState` 里只更新 ref，不直接 setState",
				"- 用一个 `requestAnimationFrame` 合并同帧内的多次滚动",
				"- 高亮 index 只有变化时才 setState",
				"",
				"预计净删代码（去掉重复的中间状态），不是加节流库。",
			].join("\n"),
			time: "11:41",
		},
		{
			id: "s1-u6",
			role: "user",
			text: "改完顺便看看消息气泡在窄窗口（小于 sm）下的表现，现在 80% 上限感觉还是有点宽。",
			time: "11:45",
		},
		{
			id: "s1-a6",
			role: "assistant",
			text: [
				"窄窗口下限制到 `max-w-[85%]` 更合适，长句换行不至于每行只有几个字：",
				"",
				"```diff",
				'- <div className="max-w-[80%] sm:max-w-[70%]">',
				'+ <div className="max-w-[85%] sm:max-w-[70%]">',
				"```",
				"",
				"时间戳和操作按钮仍在气泡上方右对齐，不受影响。",
			].join("\n"),
			time: "11:46",
		},
		{
			id: "s1-u7",
			role: "user",
			text: "行，这两个一起改了吧，我再看看整体效果。",
			time: "11:48",
		},
		{
			id: "s1-a7",
			role: "assistant",
			text: [
				"都改好了：",
				"",
				"| 改动 | 文件 | 说明 |",
				"| --- | --- | --- |",
				"| scroll 节流 | `chat-page.tsx` | rAF 合并滚动事件 |",
				"| 气泡上限 | `chat-page.tsx` | 窄窗口 85% / 桌面 70% |",
				"",
				"验证命令都过了，`tauri dev` 里重点看两处：快速滚动时 outline 高亮是否跟手，以及窄窗口下用户气泡换行观感。",
			].join("\n"),
			time: "11:49",
			activity: [
				{
					id: "s1-a7-tool-1",
					type: "tool",
					toolName: "edit",
					args: { path: "src/components/chat/chat-page.tsx" },
					status: "complete",
				},
			],
		},
		{
			id: "s1-u8",
			role: "user",
			text: "如果后面接上真实 RPC streaming，消息渲染这块还要动吗？",
			time: "12:02",
		},
		{
			id: "s1-a8",
			role: "assistant",
			text: [
				"渲染层基本不用动，换的是数据源：",
				"",
				"1. `MOCK_CONVERSATIONS` 换成 Pi JSONL 的增量事件",
				"2. `streaming` 标记由 RPC 的 `message.update` 驱动",
				"3. `activity` 来自 tool call 事件，字段结构保持一致即可",
				"",
				"Streamdown 已经处理了增量 markdown 的重渲染，长回复也不会整段重绘。唯一要注意的是自动滚动：streaming 期间保持 sticky 到底部，用户上翻就解除，这部分逻辑已经在了。",
			].join("\n"),
			time: "12:03",
		},
		{
			id: "s1-u9",
			role: "user",
			text: "好。那我先去接 Runtime 那边的事件，前端这块到时候再联调。今天的改动我先提交。",
			time: "12:10",
		},
		{
			id: "s1-a9",
			role: "assistant",
			text: "好的。提交建议拆两个：一个是滚动条对齐 + 遮挡修正，一个是 scroll 节流 + 气泡上限，方便回溯。联调时如果 JSONL 事件结构和现在的 mock 对不上，直接把样例发我就行。",
			time: "12:11",
		},
	],
	s2: [
		{
			id: "s2-u1",
			role: "user",
			text: "Connection 和 PiSession 应该怎么分层？Local、WSL、SSH 后面都要支持。",
			time: "09:42",
		},
		{
			id: "s2-a1",
			role: "assistant",
			text: "Connection 只描述运行位置；Local / WSL / SSH 都由 `ServerManager` 建立对应的 `pilo-server`，Pi、文件、Git、Session 和 Terminal 再通过统一 RPC 调用目标环境。上层 Runtime 不需要区分具体 transport。",
			time: "09:44",
			activity: ["connection.rs", "server_client.rs", "server_pi.rs"].map(
				(path, index) => ({
					id: `s2-a1-tool-${index}`,
					type: "tool" as const,
					toolName: "read",
					args: { path },
					status: "complete" as const,
				}),
			),
		},
	],
	s3: [
		{
			id: "s3-u1",
			role: "user",
			text: "Pi RPC 接入后前端应该怎么消费事件？",
			time: "16:08",
		},
		{
			id: "s3-a1",
			role: "assistant",
			text: "前端只监听统一的 `pilo://runtime` event，再按 `type` 分发。Runtime 自己负责 generation 过滤，所以 React 不需要知道旧进程的事件。\n\n当前代际关系可以写成 $g_{next} > g_{active}$，旧 generation 的事件直接丢弃。\n\n```mermaid\nflowchart LR\n  Pi[Pi RPC] --> Runtime[Pilo Runtime]\n  Runtime --> Event[pilo://runtime]\n  Event --> React[React UI]\n```",
			time: "16:09",
		},
	],
};
