[package]
name = "pilo-protocol"
version.workspace = true
edition = "2024"
build = "build.rs"

[dependencies]
prost = "0.14"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["io-util"] }

[build-dependencies]
prost-build = "0.14"
protoc-bin-vendored = "3"
